//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblmusteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblmusteri()
        {
            this.tblsatislar = new HashSet<tblsatislar>();
        }
    //29.Adým Requiredler
        public int id { get; set; }
        [Required(ErrorMessage = "Ad Alanýný Boþ Geçmeyiniz...")]
        [StringLength(30, ErrorMessage = "Bu alan 30 karakterden büyük olamaz")] //ek olarak
        public string ad { get; set; }
        [Required(ErrorMessage = "Soyad Alanýný Boþ Geçmeyiniz...")]
        public string soyad { get; set; }
        
        public string sehir { get; set; }
        public Nullable<decimal> bakiye { get; set; }
        public Nullable<bool> durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblsatislar> tblsatislar { get; set; }
    }
}
